[package]
name = "skilldeck"
version = "0.1.1"
description = "A lightweight desktop UI wrapper for the official npx skills CLI"
authors = ["SkillDeck"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
tauri-plugin-dialog = "^2"
tauri-plugin-log = "^2"
log = "^0.4"
tauri-plugin-updater = "^2"
tauri-plugin-process = "^2"
